<?php

namespace App\Http\Controllers\Api;

use App\Exceptions\ApiException;
use App\Http\Controllers\Controller;
use App\Http\Middleware\Authenticate;
use App\Models\UpgradeAgentState;
use App\Models\UpgradeRequest;
use App\Services\Authority;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

/**
 * The host-side upgrade agent's two endpoints (deploy/upgrade-agent.sh)
 * plus a read-only status view for this install's own admins. Central
 * Command does not call these -- it reads and writes the two tables
 * directly, like every other push. See the migration that created
 * `upgrade_requests` for the whole picture.
 *
 * The agent authenticates with the shared secret UPGRADE_AGENT_TOKEN
 * from .env (generated by deploy/install.sh or upgrade.sh), sent as
 * the X-Upgrade-Agent-Token header. It only ever reaches this app over
 * the loopback interface, but the token keeps a stray LAN client from
 * marking upgrades done.
 */
class UpgradeAgentController extends Controller
{
    private function requireAgentToken(Request $request): void
    {
        $expected = (string) config('websoft.upgrade_agent_token');
        if ($expected === '') {
            throw new ApiException(503, 'UPGRADE_AGENT_TOKEN is not configured on this server.');
        }
        $given = (string) $request->header('X-Upgrade-Agent-Token', '');
        if ($given === '' || ! hash_equals($expected, $given)) {
            throw new ApiException(401, 'Invalid upgrade agent token.');
        }
    }

    /**
     * Records what the host currently has checked out and what
     * origin/main is at, then hands the agent the next pending request
     * (marking it running) -- or null when there is nothing to do.
     */
    public function heartbeat(Request $request)
    {
        $this->requireAgentToken($request);

        $data = $request->validate([
            'current_sha' => 'nullable|string|max:40',
            'current_subject' => 'nullable|string|max:2000',
            'current_committed_at' => 'nullable|date',
            'remote_sha' => 'nullable|string|max:40',
            'remote_subject' => 'nullable|string|max:2000',
            'remote_committed_at' => 'nullable|date',
            'commits_behind' => 'nullable|integer|min:0',
            'agent_host' => 'nullable|string|max:200',
        ]);

        $next = DB::transaction(function () use ($data) {
            $state = UpgradeAgentState::singleton();
            $state->fill($data + ['commits_behind' => $data['commits_behind'] ?? 0]);
            $state->save();
            // Raw expressions can't go through the model's datetime cast.
            UpgradeAgentState::whereKey(1)->update(['last_heartbeat_at' => DB::raw('now()')]);

            // A request left 'running' from before a host reboot would
            // block the queue forever; fail it so the next one can go.
            // Every lifecycle timestamp here is the DATABASE clock (like
            // requested_at's useCurrent()): Central Command reads these
            // rows as UTC, and an app-side now() in Asia/Singapore was
            // 8 hours off next to requested_at.
            UpgradeRequest::where('status', UpgradeRequest::STATUS_RUNNING)
                ->whereRaw('started_at < now() - make_interval(mins => ?)', [UpgradeRequest::STALE_RUNNING_MINUTES])
                ->update([
                    'status' => UpgradeRequest::STATUS_FAILED,
                    'finished_at' => DB::raw('now()'),
                    'error' => 'The agent never reported back (host restarted or agent stopped mid-upgrade).',
                ]);

            if (UpgradeRequest::where('status', UpgradeRequest::STATUS_RUNNING)->exists()) {
                return null;
            }

            $next = UpgradeRequest::where('status', UpgradeRequest::STATUS_PENDING)
                ->orderBy('requested_at')
                ->lockForUpdate()
                ->first();
            if (! $next) {
                return null;
            }
            UpgradeRequest::whereKey($next->id)->update([
                'status' => UpgradeRequest::STATUS_RUNNING,
                'started_at' => DB::raw('now()'),
                'from_sha' => $data['current_sha'] ?? null,
            ]);

            return $next;
        });

        return response()->json([
            'request' => $next ? ['id' => $next->id, 'kind' => $next->kind, 'target_ref' => $next->target_ref] : null,
        ]);
    }

    public function report(Request $request)
    {
        $this->requireAgentToken($request);

        $data = $request->validate([
            'id' => 'required|uuid',
            'success' => 'required|boolean',
            'from_sha' => 'nullable|string|max:40',
            'to_sha' => 'nullable|string|max:40',
            'log' => 'nullable|string|max:200000',
            'error' => 'nullable|string|max:2000',
        ]);

        $req = UpgradeRequest::find($data['id']);
        if (! $req) {
            throw new ApiException(404, 'No such upgrade request.');
        }
        if ($req->status !== UpgradeRequest::STATUS_RUNNING) {
            // Already finalised (e.g. reported twice after a retry) -- idempotent.
            return response()->json(['status' => $req->status]);
        }

        $status = $data['success'] ? UpgradeRequest::STATUS_SUCCEEDED : UpgradeRequest::STATUS_FAILED;
        UpgradeRequest::whereKey($req->id)->update([
            'status' => $status,
            'finished_at' => DB::raw('now()'),
            'from_sha' => $data['from_sha'] ?? $req->from_sha,
            'to_sha' => $data['to_sha'] ?? null,
            'log' => $data['log'] ?? null,
            'error' => $data['error'] ?? null,
        ]);

        return response()->json(['status' => $status]);
    }

    /**
     * Live progress while an upgrade runs (2026-09-25): the agent sends the
     * log so far every few seconds, so Central Command's Client Upgrades
     * screen shows the current step and output as it happens instead of a
     * static "running". Only a RUNNING request is touched; the final
     * report replaces the log with the complete one.
     */
    public function progress(Request $request)
    {
        $this->requireAgentToken($request);

        $data = $request->validate([
            'id' => 'required|uuid',
            'log' => 'nullable|string|max:200000',
        ]);

        $updated = UpgradeRequest::whereKey($data['id'])
            ->where('status', UpgradeRequest::STATUS_RUNNING)
            ->update(['log' => $data['log'] ?? null]);

        return response()->json(['updated' => $updated > 0]);
    }

    /** Read-only, for this install's own administrators. */
    public function status(Request $request)
    {
        $user = Authenticate::user($request);
        Authority::requireModuleAccess($user, 'core_administration', 'view');

        $state = UpgradeAgentState::find(1);
        $active = UpgradeRequest::whereIn('status', UpgradeRequest::ACTIVE_STATUSES)->orderBy('requested_at')->first();
        $history = UpgradeRequest::orderByDesc('requested_at')->limit(20)->get();

        return response()->json([
            'agent' => $state,
            'agent_online' => $state !== null && (bool) DB::selectOne(
                'select last_heartbeat_at > now() - make_interval(mins => ?) as online from upgrade_agent_state where id = 1',
                [UpgradeAgentState::AGENT_OFFLINE_AFTER_MINUTES]
            )?->online,
            'active' => $active,
            'history' => $history,
        ]);
    }
}
