#!/usr/bin/env bash
#
# Fresh install of the Websoft Service ERP test server.
#
#   ./deploy/install.sh
#
# Generates the secrets, brings up Postgres, applies migrations, seeds
# the demo data, and starts the app. Safe to read before you run it --
# every step is a plain docker compose call.
#
# It REFUSES to run over an existing install. Upgrading is a different
# job with different risks: use ./deploy/upgrade.sh.

set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
COMPOSE="docker compose -f deploy/docker-compose.php.yml"

say()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[33m    %s\033[0m\n' "$*"; }
die()  { printf '\n\033[31mERROR: %s\033[0m\n\n' "$*" >&2; exit 1; }

# ---- checks ---------------------------------------------------------

command -v docker >/dev/null 2>&1 || die "Docker is not installed. See DEPLOY.md section 1."
docker compose version >/dev/null 2>&1 || die "This needs Docker Compose v2 ('docker compose', not 'docker-compose')."
docker info >/dev/null 2>&1 || die "The Docker daemon is not running, or this user cannot reach it (try: sudo usermod -aG docker \$USER, then log out and back in)."

if [ -f "$ROOT/.env" ]; then
  die ".env already exists, so this looks like an existing install.
       To upgrade it:        ./deploy/upgrade.sh
       To start over:        move .env aside AND remove the data volumes
                             ($COMPOSE down -v) -- THAT DELETES THE DATABASE."
fi

# ---- secrets --------------------------------------------------------

say "Generating secrets"

# APP_KEY encrypts the per-company mailbox password. Losing it makes
# those unreadable, so it is generated once and kept in .env.
APP_KEY="base64:$(openssl rand -base64 32)"
JWT_SECRET_KEY="$(openssl rand -hex 32)"
POSTGRES_PASSWORD="$(openssl rand -hex 24)"
HTTP_PORT="${HTTP_PORT:-80}"

cat > "$ROOT/.env" <<ENV
# Generated by deploy/install.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC').
# Keep this file. APP_KEY in particular: it encrypts stored mailbox
# passwords, and they cannot be read back without it.

POSTGRES_PASSWORD=$POSTGRES_PASSWORD
JWT_SECRET_KEY=$JWT_SECRET_KEY
APP_KEY=$APP_KEY
HTTP_PORT=$HTTP_PORT

# Outbound email for the "Email X" buttons and the portal login OTP.
# Leave blank and everything else still works -- Email is skipped and a
# portal invite shows its temporary password on screen instead.
SMTP_HOST=
SMTP_PORT=587
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_FROM_EMAIL=
SMTP_FROM_NAME=Web Master Consultancy
ENV
chmod 600 "$ROOT/.env"
echo "    .env written (mode 600)"

# ---- build and start ------------------------------------------------

say "Building images (first run pulls PHP, Postgres, nginx and LibreOffice -- expect several minutes)"
$COMPOSE build

say "Starting the database"
$COMPOSE up -d db

say "Applying migrations"
$COMPOSE run --rm migrate-php

say "Seeding demo data"
$COMPOSE run --rm --entrypoint php backend-php artisan db:seed --force

say "Starting the application"
$COMPOSE up -d

# ---- report ---------------------------------------------------------

say "Done"
IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
PORT_SUFFIX=""
[ "$HTTP_PORT" != "80" ] && PORT_SUFFIX=":$HTTP_PORT"
cat <<REPORT

  ERP        http://${IP:-<server-ip>}${PORT_SUFFIX}/
  Mobile     http://${IP:-<server-ip>}${PORT_SUFFIX}/mobile
  Portal     http://${IP:-<server-ip>}${PORT_SUFFIX}/portal

  Sign in as   dennis@websoft.example
  Password     demo1234

  Status        docker compose -f deploy/docker-compose.php.yml ps
  Logs          docker compose -f deploy/docker-compose.php.yml logs -f backend-php
  Upgrade       ./deploy/upgrade.sh

REPORT
warn "CHANGE THAT PASSWORD before anyone else can reach this server."
warn "This is a TEST server recipe: plain HTTP, and it seeds demo data."
warn "For anything real, add HTTPS first -- DEPLOY.md section 6."
