"""customer industry grouping

Revision ID: 01f0866fc34b
Revises: 1c0caa9bdbb3
Create Date: 2026-09-11 08:32:14.857343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f0866fc34b'
down_revision: Union[str, Sequence[str], None] = '1c0caa9bdbb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # New SetupListType value (confirmed 2026-09-11: customer grouping
    # by industry) -- autogenerate doesn't detect enum value additions,
    # added by hand, same as ContractKind.AD_HOC in 4439ad3f1684.
    op.execute("ALTER TYPE setup_list_type ADD VALUE IF NOT EXISTS 'INDUSTRY'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('industry_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'industry_code')
    # ### end Alembic commands ###
    # Note: Postgres has no ALTER TYPE ... DROP VALUE, so the
    # 'INDUSTRY' enum label added in upgrade() is not removed here.
