"""add company logo, multi-company access, company-scoped audit

Revision ID: 24cc1861aed5
Revises: 4fabe9c2203d
Create Date: 2026-09-10 02:57:12.114494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24cc1861aed5'
down_revision: Union[str, Sequence[str], None] = '4fabe9c2203d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_company_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_company')
    )
    op.add_column('audit_log_entries', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'audit_log_entries', 'companies', ['company_id'], ['id'])
    op.add_column('companies', sa.Column('logo', sa.Text(), nullable=True))
    # server_default so existing company rows backfill to "active" --
    # without it, adding a NOT NULL column to a populated table fails.
    op.add_column(
        'companies',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'is_active')
    op.drop_column('companies', 'logo')
    op.drop_constraint(None, 'audit_log_entries', type_='foreignkey')
    op.drop_column('audit_log_entries', 'company_id')
    op.drop_table('user_company_access')
    # ### end Alembic commands ###
