"""contract type ad_hoc, hourly rate, sales staff, product coverage

Revision ID: 4439ad3f1684
Revises: 6871af0364ed
Create Date: 2026-09-11 07:46:29.069933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4439ad3f1684'
down_revision: Union[str, Sequence[str], None] = '6871af0364ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # New ContractKind value (confirmed 2026-09-11) -- autogenerate
    # doesn't detect enum value additions, added by hand. Postgres 12+
    # allows this inside a transaction as long as the new value isn't
    # used by a DML statement in that same transaction (it isn't here).
    op.execute("ALTER TYPE contract_kind ADD VALUE IF NOT EXISTS 'AD_HOC'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'product_id', name='uq_contract_product')
    )
    op.add_column('contracts', sa.Column('hourly_rate_sgd', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('contracts', sa.Column('sales_staff_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'users', ['sales_staff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'sales_staff_id')
    op.drop_column('contracts', 'hourly_rate_sgd')
    op.drop_table('contract_products')
    # ### end Alembic commands ###
    # Note: Postgres has no ALTER TYPE ... DROP VALUE, so the 'AD_HOC'
    # enum label added in upgrade() is not removed here. Harmless if
    # unused; would need a full enum-type rebuild to actually remove.
