"""add event logs audit fields

Revision ID: 4fabe9c2203d
Revises: 73070a798de9
Create Date: 2026-09-10 02:27:33.857479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fabe9c2203d'
down_revision: Union[str, Sequence[str], None] = '73070a798de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log_entries', sa.Column('actor_name', sa.String(length=255), nullable=True))
    op.add_column('audit_log_entries', sa.Column('old_value', sa.Text(), nullable=True))
    op.add_column('audit_log_entries', sa.Column('new_value', sa.Text(), nullable=True))
    op.add_column('audit_log_entries', sa.Column('ip_address', sa.String(length=64), nullable=True))
    op.add_column('audit_log_entries', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.add_column('audit_log_entries', sa.Column('device_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log_entries', 'device_id')
    op.drop_column('audit_log_entries', 'user_agent')
    op.drop_column('audit_log_entries', 'ip_address')
    op.drop_column('audit_log_entries', 'new_value')
    op.drop_column('audit_log_entries', 'old_value')
    op.drop_column('audit_log_entries', 'actor_name')
    # ### end Alembic commands ###
