"""setup lists, gl types, treasury, tax code uniqueness, accounting periods

Revision ID: 6871af0364ed
Revises: adfb399e8b74
Create Date: 2026-09-11 05:04:33.415115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6871af0364ed'
down_revision: Union[str, Sequence[str], None] = 'adfb399e8b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setup_list_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('list_type', sa.Enum('NATIONALITY', 'COUNTRY', 'STATE', 'AREA_CODE', 'CURRENCY', name='setup_list_type'), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('parent_code', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_type', 'code', name='uq_setup_list_item_code')
    )
    op.create_table('currency_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('rate_to_base', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'currency_code', 'effective_date', name='uq_currency_rate')
    )
    op.create_table('gl_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    # account_type reuses the Postgres enum type already created for
    # accounts.account_type -- create_type=False so this table doesn't
    # try (and fail) to CREATE TYPE account_type a second time.
    sa.Column('account_type', postgresql.ENUM('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='account_type', create_type=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_gl_type_code')
    )
    op.create_table('accounting_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='period_status'), nullable=False),
    sa.Column('closed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_start', name='uq_accounting_period_start')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=150), nullable=False),
    sa.Column('account_name', sa.String(length=150), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('branch', sa.String(length=150), nullable=True),
    sa.Column('swift_code', sa.String(length=20), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('gl_account_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['gl_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiscal_year_closures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('retained_earnings_account_id', sa.UUID(), nullable=False),
    sa.Column('closing_journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('closed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['closing_journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['retained_earnings_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', name='uq_fiscal_year_closure')
    )
    op.add_column('accounts', sa.Column('gl_type_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'gl_types', ['gl_type_id'], ['id'])
    op.create_unique_constraint('uq_tax_code', 'tax_codes', ['company_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tax_code', 'tax_codes', type_='unique')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'gl_type_id')
    op.drop_table('fiscal_year_closures')
    op.drop_table('bank_accounts')
    op.drop_table('accounting_periods')
    op.drop_table('gl_types')
    op.drop_table('currency_rates')
    op.drop_table('setup_list_items')
    # ### end Alembic commands ###
