"""software task

Revision ID: 6967b9b7fa12
Revises: 9f81fdd0baa0
Create Date: 2026-09-10 19:32:17.107482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6967b9b7fa12'
down_revision: Union[str, Sequence[str], None] = '9f81fdd0baa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('modules_affected', sa.String(length=500), nullable=True),
    sa.Column('assigned_programmer_id', sa.UUID(), nullable=True),
    sa.Column('programming_finish_date', sa.Date(), nullable=True),
    sa.Column('programming_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('tester_user_id', sa.UUID(), nullable=True),
    sa.Column('is_tested', sa.Boolean(), nullable=False),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_programmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tester_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('software_tasks')
    # ### end Alembic commands ###
