"""GST tax codes, invoice AR fields, payments, customer payment terms

Revision ID: 99936568066a
Revises: 3af20a7d4dec
Create Date: 2026-09-10 04:06:32.222949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99936568066a'
down_revision: Union[str, Sequence[str], None] = '3af20a7d4dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('doc_kind', sa.String(length=30), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'doc_kind', 'year', name='uq_document_sequence')
    )
    op.create_table('tax_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount_sgd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('BANK_TRANSFER', 'PAYNOW', 'CHEQUE', 'CASH', 'CREDIT_CARD', 'OTHER', name='payment_method'), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount_sgd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('companies', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('gst_registration_no', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('write_off_approval_threshold_sgd', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('companies', sa.Column('credit_note_approval_threshold_sgd', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('companies', sa.Column('po_approval_threshold_sgd', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('customers', sa.Column('billing_address', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('payment_terms_days', sa.Integer(), nullable=True))
    # --- invoices ------------------------------------------------------
    # Existing invoices are live financial records, so each new NOT NULL
    # column is added nullable, backfilled, then constrained.
    #
    # Deliberate: historical invoices are backfilled with ZERO GST, not
    # 9%. They were issued before the company was set up as GST-charging,
    # and retrospectively adding tax to an already-issued invoice would
    # falsify a financial record. Their total therefore equals their net.
    op.add_column('invoices', sa.Column('invoice_number', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('tax_code', sa.String(length=10), nullable=True))
    op.add_column('invoices', sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('gst_amount_sgd', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('total_amount_sgd', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('due_date', sa.Date(), nullable=True))
    # add_column does not create the enum type for us the way create_table
    # does, so create it explicitly first.
    invoice_status = sa.Enum(
        'OUTSTANDING', 'PARTIALLY_PAID', 'PAID', 'WRITTEN_OFF', name='invoice_status'
    )
    invoice_status.create(op.get_bind(), checkfirst=True)
    op.add_column('invoices', sa.Column('status', invoice_status, nullable=True))
    op.add_column('invoices', sa.Column('amount_paid_sgd', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('is_disputed', sa.Boolean(), nullable=True))
    op.add_column('invoices', sa.Column('dispute_note', sa.String(length=500), nullable=True))

    # Number existing invoices in issue order, per company per year, so
    # they follow the same INV-<year>-<seq> convention as new ones.
    op.execute(
        """
        UPDATE invoices i SET invoice_number = n.number
        FROM (
            SELECT id,
                   'INV-' || EXTRACT(YEAR FROM issued_at)::int || '-' ||
                   LPAD(ROW_NUMBER() OVER (
                       PARTITION BY company_id, EXTRACT(YEAR FROM issued_at)
                       ORDER BY issued_at, id
                   )::text, 4, '0') AS number
            FROM invoices
        ) n
        WHERE n.id = i.id
        """
    )
    op.execute(
        "UPDATE invoices SET "
        "  tax_code = 'SR', "
        "  gst_rate = 0, "
        "  gst_amount_sgd = 0, "
        "  total_amount_sgd = amount_sgd, "
        "  amount_paid_sgd = 0, "
        "  is_disputed = false, "
        "  status = 'OUTSTANDING' "
        "WHERE tax_code IS NULL"
    )

    # Seed the numbering counters so newly issued invoices continue from
    # the numbers just assigned rather than colliding with them.
    op.execute(
        """
        INSERT INTO document_sequences (id, company_id, doc_kind, year, last_number)
        SELECT gen_random_uuid(), company_id, 'invoice',
               EXTRACT(YEAR FROM issued_at)::int, COUNT(*)
        FROM invoices
        GROUP BY company_id, EXTRACT(YEAR FROM issued_at)
        """
    )

    for column in (
        'invoice_number', 'tax_code', 'gst_rate', 'gst_amount_sgd',
        'total_amount_sgd', 'status', 'amount_paid_sgd', 'is_disputed',
    ):
        op.alter_column('invoices', column, nullable=False)

    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_column('invoices', 'dispute_note')
    op.drop_column('invoices', 'is_disputed')
    op.drop_column('invoices', 'amount_paid_sgd')
    op.drop_column('invoices', 'status')
    op.drop_column('invoices', 'due_date')
    op.drop_column('invoices', 'total_amount_sgd')
    op.drop_column('invoices', 'gst_amount_sgd')
    op.drop_column('invoices', 'gst_rate')
    op.drop_column('invoices', 'tax_code')
    op.drop_column('invoices', 'invoice_number')
    op.drop_column('customers', 'payment_terms_days')
    op.drop_column('customers', 'billing_address')
    op.drop_column('companies', 'po_approval_threshold_sgd')
    op.drop_column('companies', 'credit_note_approval_threshold_sgd')
    op.drop_column('companies', 'write_off_approval_threshold_sgd')
    op.drop_column('companies', 'gst_registration_no')
    op.drop_column('companies', 'address')
    op.drop_table('payment_allocations')
    op.drop_table('payments')
    op.drop_table('tax_codes')
    op.drop_table('document_sequences')
    # ### end Alembic commands ###
