"""job order due date

Revision ID: 9f81fdd0baa0
Revises: c64ca3ec7e20
Create Date: 2026-09-10 15:49:57.167579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f81fdd0baa0'
down_revision: Union[str, Sequence[str], None] = 'c64ca3ec7e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_orders', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_orders', 'due_date')
    # ### end Alembic commands ###
