"""company phone, website, uen for printed form letterhead

Revision ID: adfb399e8b74
Revises: 6967b9b7fa12
Create Date: 2026-09-10 20:04:46.914653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfb399e8b74'
down_revision: Union[str, Sequence[str], None] = '6967b9b7fa12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('phone', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('uen', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'uen')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'phone')
    # ### end Alembic commands ###
