"""GL posting + Bank step (ACC-001..004)

Revision ID: b7c8d9e0f1a2
Revises: dfd036f77dd0
Create Date: 2026-09-14

Schema for docs/gl-posting-design.md §5:

- payments.bank_account_id, supplier_payments.bank_account_id
  (FK bank_accounts). Back-filled to the company's oldest active bank
  account. Left NULLABLE at the DB level on purpose: a company with
  existing vouchers but no bank account would otherwise make this
  migration fail, and a migration must never invent a bank account.
  The API requires the field on every new voucher instead.
- supplier_invoices.expense_account_id (FK accounts), nullable; the
  posting service defaults to 5000 Cost of services.
- bank_transactions.source_type / source_id -- link back to the voucher
  that the Bank step created the line from.
- Partial unique index on journal_entries (source_type, source_id)
  WHERE status <> 'REVERSED': a document can have at most one live
  posting. journal_status is a native enum that stores the Python
  member NAME, hence the uppercase literal (see DEV_SETUP.md,
  "Native enums are the usual culprit").

Hand-written, not autogenerated -- see DEV_SETUP.md for why.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


revision = "b7c8d9e0f1a2"
down_revision = "dfd036f77dd0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── bank account on receipts and supplier payments ────────────────
    op.add_column(
        "payments",
        sa.Column("bank_account_id", UUID(as_uuid=True), sa.ForeignKey("bank_accounts.id"), nullable=True),
    )
    op.add_column(
        "supplier_payments",
        sa.Column("bank_account_id", UUID(as_uuid=True), sa.ForeignKey("bank_accounts.id"), nullable=True),
    )
    op.create_index("ix_payments_bank_account_id", "payments", ["bank_account_id"])
    op.create_index("ix_supplier_payments_bank_account_id", "supplier_payments", ["bank_account_id"])

    # Back-fill: each company's oldest active bank account. Rows for a
    # company with no bank account stay NULL (see module docstring).
    backfill = """
        UPDATE {table} p
        SET bank_account_id = b.id
        FROM (
            SELECT DISTINCT ON (company_id) id, company_id
            FROM bank_accounts
            WHERE is_active = true
            ORDER BY company_id, created_at
        ) b
        WHERE p.company_id = b.company_id
          AND p.bank_account_id IS NULL
    """
    op.execute(backfill.format(table="payments"))
    op.execute(backfill.format(table="supplier_payments"))

    # ── expense account on supplier bills ─────────────────────────────
    op.add_column(
        "supplier_invoices",
        sa.Column("expense_account_id", UUID(as_uuid=True), sa.ForeignKey("accounts.id"), nullable=True),
    )

    # ── bank book lines remember their source voucher ─────────────────
    op.add_column("bank_transactions", sa.Column("source_type", sa.String(50), nullable=True))
    op.add_column("bank_transactions", sa.Column("source_id", UUID(as_uuid=True), nullable=True))
    op.create_index(
        "ix_bank_transactions_source", "bank_transactions", ["source_type", "source_id"]
    )

    # ── one live posting per document ─────────────────────────────────
    op.create_index(
        "uq_journal_entries_live_source",
        "journal_entries",
        ["source_type", "source_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'REVERSED' AND source_type IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index("uq_journal_entries_live_source", table_name="journal_entries")
    op.drop_index("ix_bank_transactions_source", table_name="bank_transactions")
    op.drop_column("bank_transactions", "source_id")
    op.drop_column("bank_transactions", "source_type")
    op.drop_column("supplier_invoices", "expense_account_id")
    op.drop_index("ix_supplier_payments_bank_account_id", table_name="supplier_payments")
    op.drop_index("ix_payments_bank_account_id", table_name="payments")
    op.drop_column("supplier_payments", "bank_account_id")
    op.drop_column("payments", "bank_account_id")
