"""customer relationships

Revision ID: c2b41b06fd17
Revises: a025ca222e9c
Create Date: 2026-09-11 15:43:19.657270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b41b06fd17'
down_revision: Union[str, Sequence[str], None] = 'a025ca222e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('from_customer_id', sa.UUID(), nullable=False),
    sa.Column('to_customer_id', sa.UUID(), nullable=True),
    sa.Column('to_contact_id', sa.UUID(), nullable=True),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['to_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['to_customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_relationships')
    # ### end Alembic commands ###
