"""Customer Helpdesk Portal (PORTAL-001..004)

Revision ID: c8d9e0f1a2b3
Revises: b7c8d9e0f1a2
Create Date: 2026-09-14

Schema for docs/customer-portal-design.md §3:

- portal_users: one login per Contact, in its own table (PORTAL-001,
  PORTAL-003).
- login_otps.user_id becomes nullable and login_otps.portal_user_id is
  added -- one OTP table serves staff and portal logins; exactly one of
  the two is set.
- incidents.raised_by_portal_user_id -- who at the customer raised it.
- incident_source gains 'PORTAL'. The native enum stores the Python
  member NAME, hence uppercase (see DEV_SETUP.md, "Native enums are the
  usual culprit"). Postgres cannot drop an enum value, so downgrade
  leaves the label in place -- harmless, nothing references it after the
  column changes are reverted.

Hand-written, not autogenerated -- see DEV_SETUP.md for why.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


revision = "c8d9e0f1a2b3"
down_revision = "b7c8d9e0f1a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "portal_users",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("company_id", UUID(as_uuid=True), sa.ForeignKey("companies.id"), nullable=False),
        sa.Column("contact_id", UUID(as_uuid=True), sa.ForeignKey("contacts.id"), nullable=False),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("must_change_password", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("failed_attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("contact_id", name="uq_portal_user_contact"),
        sa.UniqueConstraint("company_id", "email", name="uq_portal_user_company_email"),
    )
    op.create_index("ix_portal_users_company_id", "portal_users", ["company_id"])

    # One OTP table for both logins.
    op.alter_column("login_otps", "user_id", existing_type=UUID(as_uuid=True), nullable=True)
    op.add_column(
        "login_otps",
        sa.Column("portal_user_id", UUID(as_uuid=True), sa.ForeignKey("portal_users.id"), nullable=True),
    )
    op.create_index("ix_login_otps_portal_user_id", "login_otps", ["portal_user_id"])

    op.add_column(
        "incidents",
        sa.Column("raised_by_portal_user_id", UUID(as_uuid=True), sa.ForeignKey("portal_users.id"), nullable=True),
    )

    # Uppercase: incident_source stores enum member names. IF NOT EXISTS
    # keeps this idempotent. A value added in a transaction cannot be
    # used until it commits; nothing here uses it.
    op.execute("ALTER TYPE incident_source ADD VALUE IF NOT EXISTS 'PORTAL'")


def downgrade() -> None:
    op.drop_column("incidents", "raised_by_portal_user_id")
    op.drop_index("ix_login_otps_portal_user_id", table_name="login_otps")
    op.drop_column("login_otps", "portal_user_id")
    # Rows that belonged to portal users must go before user_id becomes
    # NOT NULL again; they are unusable without the portal anyway.
    op.execute("DELETE FROM login_otps WHERE user_id IS NULL")
    op.alter_column("login_otps", "user_id", existing_type=UUID(as_uuid=True), nullable=False)
    op.drop_index("ix_portal_users_company_id", table_name="portal_users")
    op.drop_table("portal_users")
    # 'PORTAL' stays in incident_source: Postgres cannot drop an enum value.
