"""add supplier phone

Revision ID: ca1ddfca6a83
Revises: 08ceed0e5b5d
Create Date: 2026-09-12 00:29:01.676232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca1ddfca6a83'
down_revision: Union[str, Sequence[str], None] = '08ceed0e5b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'phone')
    # ### end Alembic commands ###
