"""document number format customization

Revision ID: cc953b888c6b
Revises: 01f0866fc34b
Create Date: 2026-09-11 08:50:03.575321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc953b888c6b'
down_revision: Union[str, Sequence[str], None] = '01f0866fc34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_number_formats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('doc_kind', sa.String(length=30), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('number_length', sa.Integer(), nullable=False),
    sa.Column('include_year', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'doc_kind', name='uq_document_number_format')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_number_formats')
    # ### end Alembic commands ###
