"""general ledger vouchers and accounts payable

Revision ID: fcce9f5d7a06
Revises: 1dc36a6d0e5a
Create Date: 2026-09-10 06:01:27.554042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcce9f5d7a06'
down_revision: Union[str, Sequence[str], None] = '1dc36a6d0e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gst_registration_no', sa.String(length=50), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('voucher_number', sa.String(length=50), nullable=False),
    sa.Column('voucher_type', sa.Enum('JOURNAL', 'RECEIPT', 'PAYMENT', 'SALES_INVOICE', 'PURCHASE_INVOICE', name='voucher_type'), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('narration', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'REVERSED', name='journal_status'), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('reverses_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('posted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reverses_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_voucher_number'), 'journal_entries', ['voucher_number'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount_sgd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_amount_sgd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount_sgd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'CANCELLED', name='purchase_order_status'), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=False)
    op.create_table('supplier_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('voucher_number', sa.String(length=50), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount_sgd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('paid_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['paid_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_payments_voucher_number'), 'supplier_payments', ['voucher_number'], unique=False)
    op.create_table('journal_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('debit_sgd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('credit_sgd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_invoice_no', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount_sgd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_amount_sgd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount_sgd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid_sgd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('match_status', sa.Enum('NOT_MATCHED', 'MATCHED', 'EXCEPTION', name='bill_match_status'), nullable=False),
    sa.Column('match_note', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('AWAITING_MATCH', 'EXCEPTION', 'APPROVED', 'PARTIALLY_PAID', 'PAID', name='bill_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_invoices_bill_number'), 'supplier_invoices', ['bill_number'], unique=False)
    op.create_table('supplier_payment_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('supplier_invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount_sgd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['supplier_payments.id'], ),
    sa.ForeignKeyConstraint(['supplier_invoice_id'], ['supplier_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Existing receipts predate voucher numbering, so number them in
    # receipt order per company per year, then constrain -- rather than
    # failing NOT NULL on a populated table.
    op.add_column('payments', sa.Column('voucher_number', sa.String(length=50), nullable=True))
    op.execute(
        """
        UPDATE payments p SET voucher_number = n.number
        FROM (
            SELECT id,
                   'RV-' || EXTRACT(YEAR FROM payment_date)::int || '-' ||
                   LPAD(ROW_NUMBER() OVER (
                       PARTITION BY company_id, EXTRACT(YEAR FROM payment_date)
                       ORDER BY payment_date, created_at, id
                   )::text, 4, '0') AS number
            FROM payments
        ) n
        WHERE n.id = p.id
        """
    )
    # Continue the numbering sequence from those numbers instead of
    # colliding with them when the next receipt is recorded.
    op.execute(
        """
        INSERT INTO document_sequences (id, company_id, doc_kind, year, last_number)
        SELECT gen_random_uuid(), company_id, 'receipt',
               EXTRACT(YEAR FROM payment_date)::int, COUNT(*)
        FROM payments
        GROUP BY company_id, EXTRACT(YEAR FROM payment_date)
        ON CONFLICT (company_id, doc_kind, year) DO UPDATE
        SET last_number = GREATEST(document_sequences.last_number, EXCLUDED.last_number)
        """
    )
    op.alter_column('payments', 'voucher_number', nullable=False)
    op.create_index(op.f('ix_payments_voucher_number'), 'payments', ['voucher_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_voucher_number'), table_name='payments')
    op.drop_column('payments', 'voucher_number')
    op.drop_table('supplier_payment_allocations')
    op.drop_index(op.f('ix_supplier_invoices_bill_number'), table_name='supplier_invoices')
    op.drop_table('supplier_invoices')
    op.drop_table('journal_lines')
    op.drop_index(op.f('ix_supplier_payments_voucher_number'), table_name='supplier_payments')
    op.drop_table('supplier_payments')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_journal_entries_voucher_number'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
